package com.yuman.dao;

import com.yuman.bean.SAddress;
import com.yuman.bean.SAddressExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SAddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    long countByExample(SAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int deleteByExample(SAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int insert(SAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int insertSelective(SAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    List<SAddress> selectByExample(SAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    SAddress selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") SAddress record, @Param("example") SAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByExample(@Param("record") SAddress record, @Param("example") SAddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByPrimaryKeySelective(SAddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByPrimaryKey(SAddress record);
}