package com.yuman.dao;

import com.yuman.bean.SCate;
import com.yuman.bean.SCateExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SCateMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    long countByExample(SCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int deleteByExample(SCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int insert(SCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int insertSelective(SCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    List<SCate> selectByExample(SCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    SCate selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") SCate record, @Param("example") SCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByExample(@Param("record") SCate record, @Param("example") SCateExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByPrimaryKeySelective(SCate record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByPrimaryKey(SCate record);
}