package com.yuman.dao;

import com.yuman.bean.SOrder;
import com.yuman.bean.SOrderExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    long countByExample(SOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    int deleteByExample(SOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    int insert(SOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    int insertSelective(SOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    List<SOrder> selectByExample(SOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    SOrder selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    int updateByExampleSelective(@Param("record") SOrder record, @Param("example") SOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    int updateByExample(@Param("record") SOrder record, @Param("example") SOrderExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    int updateByPrimaryKeySelective(SOrder record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ORDER
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    int updateByPrimaryKey(SOrder record);
}