package com.yuman.dao;

import com.yuman.bean.SShopcartItem;
import com.yuman.bean.SShopcartItemExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SShopcartItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    long countByExample(SShopcartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int deleteByExample(SShopcartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int insert(SShopcartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int insertSelective(SShopcartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    List<SShopcartItem> selectByExample(SShopcartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    SShopcartItem selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") SShopcartItem record, @Param("example") SShopcartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByExample(@Param("record") SShopcartItem record, @Param("example") SShopcartItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByPrimaryKeySelective(SShopcartItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_SHOPCART_ITEM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByPrimaryKey(SShopcartItem record);
}