package com.yuman.dao;

import com.yuman.bean.SUser;
import com.yuman.bean.SUserExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    long countByExample(SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int deleteByExample(SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int deleteByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int insert(SUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int insertSelective(SUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    List<SUser> selectByExample(SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    SUser selectByPrimaryKey(BigDecimal id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByExampleSelective(@Param("record") SUser record, @Param("example") SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByExample(@Param("record") SUser record, @Param("example") SUserExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByPrimaryKeySelective(SUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_USER
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    int updateByPrimaryKey(SUser record);
}