package com.yuman.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class Orderline implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERLINE.ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERLINE.NUM
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private BigDecimal num;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERLINE.ORDER_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private BigDecimal orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERLINE.PRODUCT_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private BigDecimal productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ORDERLINE.USER_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private BigDecimal userId;
    
    private Product product;
    
    private SOrder order;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ORDERLINE
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERLINE.ID
     *
     * @return the value of ORDERLINE.ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERLINE.ID
     *
     * @param id the value for ORDERLINE.ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERLINE.NUM
     *
     * @return the value of ORDERLINE.NUM
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public BigDecimal getNum() {
        return num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERLINE.NUM
     *
     * @param num the value for ORDERLINE.NUM
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setNum(BigDecimal num) {
        this.num = num;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERLINE.ORDER_ID
     *
     * @return the value of ORDERLINE.ORDER_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public BigDecimal getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERLINE.ORDER_ID
     *
     * @param orderId the value for ORDERLINE.ORDER_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setOrderId(BigDecimal orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERLINE.PRODUCT_ID
     *
     * @return the value of ORDERLINE.PRODUCT_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public BigDecimal getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERLINE.PRODUCT_ID
     *
     * @param productId the value for ORDERLINE.PRODUCT_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setProductId(BigDecimal productId) {
        this.productId = productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ORDERLINE.USER_ID
     *
     * @return the value of ORDERLINE.USER_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ORDERLINE.USER_ID
     *
     * @param userId the value for ORDERLINE.USER_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }
    

    public Product getProduct() {
		return product;
	}

	public void setProduct(Product product) {
		this.product = product;
	}

	public SOrder getOrder() {
		return order;
	}

	public void setOrder(SOrder order) {
		this.order = order;
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ORDERLINE
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", num=").append(num);
        sb.append(", orderId=").append(orderId);
        sb.append(", productId=").append(productId);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}