package com.yuman.bean;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class ProductExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public ProductExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("ID is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("ID is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(BigDecimal value) {
            addCriterion("ID =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(BigDecimal value) {
            addCriterion("ID <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(BigDecimal value) {
            addCriterion("ID >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("ID >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(BigDecimal value) {
            addCriterion("ID <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("ID <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<BigDecimal> values) {
            addCriterion("ID in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<BigDecimal> values) {
            addCriterion("ID not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("ID not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("NAME is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("NAME is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("NAME =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("NAME <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("NAME >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("NAME >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("NAME <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("NAME <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("NAME like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("NAME not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("NAME in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("NAME not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("NAME between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("NAME not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andPriceIsNull() {
            addCriterion("PRICE is null");
            return (Criteria) this;
        }

        public Criteria andPriceIsNotNull() {
            addCriterion("PRICE is not null");
            return (Criteria) this;
        }

        public Criteria andPriceEqualTo(BigDecimal value) {
            addCriterion("PRICE =", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotEqualTo(BigDecimal value) {
            addCriterion("PRICE <>", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThan(BigDecimal value) {
            addCriterion("PRICE >", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE >=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThan(BigDecimal value) {
            addCriterion("PRICE <", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("PRICE <=", value, "price");
            return (Criteria) this;
        }

        public Criteria andPriceIn(List<BigDecimal> values) {
            addCriterion("PRICE in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotIn(List<BigDecimal> values) {
            addCriterion("PRICE not in", values, "price");
            return (Criteria) this;
        }

        public Criteria andPriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andPriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("PRICE not between", value1, value2, "price");
            return (Criteria) this;
        }

        public Criteria andImgIsNull() {
            addCriterion("IMG is null");
            return (Criteria) this;
        }

        public Criteria andImgIsNotNull() {
            addCriterion("IMG is not null");
            return (Criteria) this;
        }

        public Criteria andImgEqualTo(String value) {
            addCriterion("IMG =", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotEqualTo(String value) {
            addCriterion("IMG <>", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThan(String value) {
            addCriterion("IMG >", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgGreaterThanOrEqualTo(String value) {
            addCriterion("IMG >=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThan(String value) {
            addCriterion("IMG <", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLessThanOrEqualTo(String value) {
            addCriterion("IMG <=", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgLike(String value) {
            addCriterion("IMG like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotLike(String value) {
            addCriterion("IMG not like", value, "img");
            return (Criteria) this;
        }

        public Criteria andImgIn(List<String> values) {
            addCriterion("IMG in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotIn(List<String> values) {
            addCriterion("IMG not in", values, "img");
            return (Criteria) this;
        }

        public Criteria andImgBetween(String value1, String value2) {
            addCriterion("IMG between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andImgNotBetween(String value1, String value2) {
            addCriterion("IMG not between", value1, value2, "img");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNull() {
            addCriterion("INTRODUCTION is null");
            return (Criteria) this;
        }

        public Criteria andIntroductionIsNotNull() {
            addCriterion("INTRODUCTION is not null");
            return (Criteria) this;
        }

        public Criteria andIntroductionEqualTo(String value) {
            addCriterion("INTRODUCTION =", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotEqualTo(String value) {
            addCriterion("INTRODUCTION <>", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThan(String value) {
            addCriterion("INTRODUCTION >", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionGreaterThanOrEqualTo(String value) {
            addCriterion("INTRODUCTION >=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThan(String value) {
            addCriterion("INTRODUCTION <", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLessThanOrEqualTo(String value) {
            addCriterion("INTRODUCTION <=", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionLike(String value) {
            addCriterion("INTRODUCTION like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotLike(String value) {
            addCriterion("INTRODUCTION not like", value, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionIn(List<String> values) {
            addCriterion("INTRODUCTION in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotIn(List<String> values) {
            addCriterion("INTRODUCTION not in", values, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionBetween(String value1, String value2) {
            addCriterion("INTRODUCTION between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andIntroductionNotBetween(String value1, String value2) {
            addCriterion("INTRODUCTION not between", value1, value2, "introduction");
            return (Criteria) this;
        }

        public Criteria andHotIsNull() {
            addCriterion("HOT is null");
            return (Criteria) this;
        }

        public Criteria andHotIsNotNull() {
            addCriterion("HOT is not null");
            return (Criteria) this;
        }

        public Criteria andHotEqualTo(BigDecimal value) {
            addCriterion("HOT =", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotEqualTo(BigDecimal value) {
            addCriterion("HOT <>", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotGreaterThan(BigDecimal value) {
            addCriterion("HOT >", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("HOT >=", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotLessThan(BigDecimal value) {
            addCriterion("HOT <", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotLessThanOrEqualTo(BigDecimal value) {
            addCriterion("HOT <=", value, "hot");
            return (Criteria) this;
        }

        public Criteria andHotIn(List<BigDecimal> values) {
            addCriterion("HOT in", values, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotIn(List<BigDecimal> values) {
            addCriterion("HOT not in", values, "hot");
            return (Criteria) this;
        }

        public Criteria andHotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HOT between", value1, value2, "hot");
            return (Criteria) this;
        }

        public Criteria andHotNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("HOT not between", value1, value2, "hot");
            return (Criteria) this;
        }

        public Criteria andRemainIsNull() {
            addCriterion("REMAIN is null");
            return (Criteria) this;
        }

        public Criteria andRemainIsNotNull() {
            addCriterion("REMAIN is not null");
            return (Criteria) this;
        }

        public Criteria andRemainEqualTo(BigDecimal value) {
            addCriterion("REMAIN =", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainNotEqualTo(BigDecimal value) {
            addCriterion("REMAIN <>", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainGreaterThan(BigDecimal value) {
            addCriterion("REMAIN >", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("REMAIN >=", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainLessThan(BigDecimal value) {
            addCriterion("REMAIN <", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainLessThanOrEqualTo(BigDecimal value) {
            addCriterion("REMAIN <=", value, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainIn(List<BigDecimal> values) {
            addCriterion("REMAIN in", values, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainNotIn(List<BigDecimal> values) {
            addCriterion("REMAIN not in", values, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REMAIN between", value1, value2, "remain");
            return (Criteria) this;
        }

        public Criteria andRemainNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("REMAIN not between", value1, value2, "remain");
            return (Criteria) this;
        }

        public Criteria andSellnumIsNull() {
            addCriterion("SELLNUM is null");
            return (Criteria) this;
        }

        public Criteria andSellnumIsNotNull() {
            addCriterion("SELLNUM is not null");
            return (Criteria) this;
        }

        public Criteria andSellnumEqualTo(BigDecimal value) {
            addCriterion("SELLNUM =", value, "sellnum");
            return (Criteria) this;
        }

        public Criteria andSellnumNotEqualTo(BigDecimal value) {
            addCriterion("SELLNUM <>", value, "sellnum");
            return (Criteria) this;
        }

        public Criteria andSellnumGreaterThan(BigDecimal value) {
            addCriterion("SELLNUM >", value, "sellnum");
            return (Criteria) this;
        }

        public Criteria andSellnumGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("SELLNUM >=", value, "sellnum");
            return (Criteria) this;
        }

        public Criteria andSellnumLessThan(BigDecimal value) {
            addCriterion("SELLNUM <", value, "sellnum");
            return (Criteria) this;
        }

        public Criteria andSellnumLessThanOrEqualTo(BigDecimal value) {
            addCriterion("SELLNUM <=", value, "sellnum");
            return (Criteria) this;
        }

        public Criteria andSellnumIn(List<BigDecimal> values) {
            addCriterion("SELLNUM in", values, "sellnum");
            return (Criteria) this;
        }

        public Criteria andSellnumNotIn(List<BigDecimal> values) {
            addCriterion("SELLNUM not in", values, "sellnum");
            return (Criteria) this;
        }

        public Criteria andSellnumBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SELLNUM between", value1, value2, "sellnum");
            return (Criteria) this;
        }

        public Criteria andSellnumNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("SELLNUM not between", value1, value2, "sellnum");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdIsNull() {
            addCriterion("CATE_DETAIL_ID is null");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdIsNotNull() {
            addCriterion("CATE_DETAIL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdEqualTo(BigDecimal value) {
            addCriterion("CATE_DETAIL_ID =", value, "cateDetailId");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdNotEqualTo(BigDecimal value) {
            addCriterion("CATE_DETAIL_ID <>", value, "cateDetailId");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdGreaterThan(BigDecimal value) {
            addCriterion("CATE_DETAIL_ID >", value, "cateDetailId");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("CATE_DETAIL_ID >=", value, "cateDetailId");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdLessThan(BigDecimal value) {
            addCriterion("CATE_DETAIL_ID <", value, "cateDetailId");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("CATE_DETAIL_ID <=", value, "cateDetailId");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdIn(List<BigDecimal> values) {
            addCriterion("CATE_DETAIL_ID in", values, "cateDetailId");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdNotIn(List<BigDecimal> values) {
            addCriterion("CATE_DETAIL_ID not in", values, "cateDetailId");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CATE_DETAIL_ID between", value1, value2, "cateDetailId");
            return (Criteria) this;
        }

        public Criteria andCateDetailIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("CATE_DETAIL_ID not between", value1, value2, "cateDetailId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRODUCT
     *
     * @mbg.generated do_not_delete_during_merge Sun May 19 20:26:50 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table PRODUCT
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}