package com.yuman.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class Product implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.NAME
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.PRICE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private BigDecimal price;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.IMG
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.INTRODUCTION
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private String introduction;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.HOT
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private BigDecimal hot;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.REMAIN
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private BigDecimal remain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.SELLNUM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private BigDecimal sellnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PRODUCT.CATE_DETAIL_ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private BigDecimal cateDetailId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table PRODUCT
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.ID
     *
     * @return the value of PRODUCT.ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.ID
     *
     * @param id the value for PRODUCT.ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.NAME
     *
     * @return the value of PRODUCT.NAME
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.NAME
     *
     * @param name the value for PRODUCT.NAME
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.PRICE
     *
     * @return the value of PRODUCT.PRICE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public BigDecimal getPrice() {
        return price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.PRICE
     *
     * @param price the value for PRODUCT.PRICE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.IMG
     *
     * @return the value of PRODUCT.IMG
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.IMG
     *
     * @param img the value for PRODUCT.IMG
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setImg(String img) {
        this.img = img == null ? null : img.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.INTRODUCTION
     *
     * @return the value of PRODUCT.INTRODUCTION
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public String getIntroduction() {
        return introduction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.INTRODUCTION
     *
     * @param introduction the value for PRODUCT.INTRODUCTION
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setIntroduction(String introduction) {
        this.introduction = introduction == null ? null : introduction.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.HOT
     *
     * @return the value of PRODUCT.HOT
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public BigDecimal getHot() {
        return hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.HOT
     *
     * @param hot the value for PRODUCT.HOT
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setHot(BigDecimal hot) {
        this.hot = hot;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.REMAIN
     *
     * @return the value of PRODUCT.REMAIN
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public BigDecimal getRemain() {
        return remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.REMAIN
     *
     * @param remain the value for PRODUCT.REMAIN
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setRemain(BigDecimal remain) {
        this.remain = remain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.SELLNUM
     *
     * @return the value of PRODUCT.SELLNUM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public BigDecimal getSellnum() {
        return sellnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.SELLNUM
     *
     * @param sellnum the value for PRODUCT.SELLNUM
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setSellnum(BigDecimal sellnum) {
        this.sellnum = sellnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PRODUCT.CATE_DETAIL_ID
     *
     * @return the value of PRODUCT.CATE_DETAIL_ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public BigDecimal getCateDetailId() {
        return cateDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PRODUCT.CATE_DETAIL_ID
     *
     * @param cateDetailId the value for PRODUCT.CATE_DETAIL_ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setCateDetailId(BigDecimal cateDetailId) {
        this.cateDetailId = cateDetailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PRODUCT
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", price=").append(price);
        sb.append(", img=").append(img);
        sb.append(", introduction=").append(introduction);
        sb.append(", hot=").append(hot);
        sb.append(", remain=").append(remain);
        sb.append(", sellnum=").append(sellnum);
        sb.append(", cateDetailId=").append(cateDetailId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}