package com.yuman.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class SAddress implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_ADDRESS.ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_ADDRESS.R_NAME
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private String rName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_ADDRESS.R_PHONE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private String rPhone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_ADDRESS.ZIP
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private String zip;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_ADDRESS.R_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private String rAddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_ADDRESS.USER_ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDRESS.ID
     *
     * @return the value of S_ADDRESS.ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDRESS.ID
     *
     * @param id the value for S_ADDRESS.ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDRESS.R_NAME
     *
     * @return the value of S_ADDRESS.R_NAME
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public String getrName() {
        return rName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDRESS.R_NAME
     *
     * @param rName the value for S_ADDRESS.R_NAME
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setrName(String rName) {
        this.rName = rName == null ? null : rName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDRESS.R_PHONE
     *
     * @return the value of S_ADDRESS.R_PHONE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public String getrPhone() {
        return rPhone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDRESS.R_PHONE
     *
     * @param rPhone the value for S_ADDRESS.R_PHONE
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setrPhone(String rPhone) {
        this.rPhone = rPhone == null ? null : rPhone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDRESS.ZIP
     *
     * @return the value of S_ADDRESS.ZIP
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public String getZip() {
        return zip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDRESS.ZIP
     *
     * @param zip the value for S_ADDRESS.ZIP
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setZip(String zip) {
        this.zip = zip == null ? null : zip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDRESS.R_ADDRESS
     *
     * @return the value of S_ADDRESS.R_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public String getrAddress() {
        return rAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDRESS.R_ADDRESS
     *
     * @param rAddress the value for S_ADDRESS.R_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setrAddress(String rAddress) {
        this.rAddress = rAddress == null ? null : rAddress.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_ADDRESS.USER_ID
     *
     * @return the value of S_ADDRESS.USER_ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_ADDRESS.USER_ID
     *
     * @param userId the value for S_ADDRESS.USER_ID
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_ADDRESS
     *
     * @mbg.generated Mon May 06 02:06:24 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", rName=").append(rName);
        sb.append(", rPhone=").append(rPhone);
        sb.append(", zip=").append(zip);
        sb.append(", rAddress=").append(rAddress);
        sb.append(", userId=").append(userId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}