package com.yuman.bean;

import java.io.Serializable;
import java.math.BigDecimal;

public class SCateDetail implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_CATE_DETAIL.ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private BigDecimal id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_CATE_DETAIL.NAME
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column S_CATE_DETAIL.CATEGORY_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private BigDecimal categoryId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table S_CATE_DETAIL
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_CATE_DETAIL.ID
     *
     * @return the value of S_CATE_DETAIL.ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public BigDecimal getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_CATE_DETAIL.ID
     *
     * @param id the value for S_CATE_DETAIL.ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setId(BigDecimal id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_CATE_DETAIL.NAME
     *
     * @return the value of S_CATE_DETAIL.NAME
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_CATE_DETAIL.NAME
     *
     * @param name the value for S_CATE_DETAIL.NAME
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column S_CATE_DETAIL.CATEGORY_ID
     *
     * @return the value of S_CATE_DETAIL.CATEGORY_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public BigDecimal getCategoryId() {
        return categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column S_CATE_DETAIL.CATEGORY_ID
     *
     * @param categoryId the value for S_CATE_DETAIL.CATEGORY_ID
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    public void setCategoryId(BigDecimal categoryId) {
        this.categoryId = categoryId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table S_CATE_DETAIL
     *
     * @mbg.generated Sun May 19 20:26:50 CST 2019
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", name=").append(name);
        sb.append(", categoryId=").append(categoryId);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}